#!/usr/bin/env bash
# Intacct environment template (no secrets). Fill via your secret manager or local .env and source it.

export INTACCT_SENDER_ID="<INTACCT_SENDER_ID>"
export INTACCT_SENDER_REDACTED
export INTACCT_COMPANY_ID="<INTACCT_COMPANY_ID>"
export INTACCT_USER_ID="<INTACCT_USER_ID>"
export INTACCT_WS_USER_REDACTED

# Optional per-environment overrides
# export INTACCT_COMPANY_ID_DEV="<INTACCT_COMPANY_ID_DEV>"
# export INTACCT_USER_ID_DEV="<INTACCT_USER_ID_DEV>"
# export INTACCT_WS_USER_PASSWORD_DEV="<INTACCT_WS_USER_PASSWORD_DEV>"
# export INTACCT_COMPANY_ID_SANDBOX="<INTACCT_COMPANY_ID_SANDBOX>"
# export INTACCT_USER_ID_SANDBOX="<INTACCT_USER_ID_SANDBOX>"
# export INTACCT_WS_USER_PASSWORD_SANDBOX="<INTACCT_WS_USER_PASSWORD_SANDBOX>"
# export INTACCT_COMPANY_ID_PROD="<INTACCT_COMPANY_ID_PROD>"
# export INTACCT_USER_ID_PROD="<INTACCT_USER_ID_PROD>"
# export INTACCT_WS_USER_PASSWORD_PROD="<INTACCT_WS_USER_PASSWORD_PROD>"
